### ISSUE TITLE
Убрать пункт про выбрасывание исключения для методов названия которых начинаются c check и validate

### ISSUE THREAD

**Issue by tolvinskii** [Infinitiweb/code-conventions#8]
Предлагаю выпилить этот пункт
https://github.com/Infinitiweb/code-conventions/blob/master/PHP.md#-Методы-названия-которых-начинаются-c-check-и-validate-должны-выбрасывать-исключения-и-не-возвращать-значения

в yii2 свои функции валидации должны возвращать bool

пример кода в модели 
в rules
`[['inn'], 'validateInn']`

`
    public function validateInn()
    {
        if (...) return true;
        return false;
    }`

**Comment by hello-omny** [comment]
[Создание Валидаторов в Yii2](https://github.com/yiisoft/yii2/blob/master/docs/guide-ru/input-validation.md#%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%92%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2-)

Просто в данном случае addError === исключение, и можно жить дальше. Либо вносим поправку что для Yii2 разрешено и допустимо.
